all: esapi_startup_getrandom_mssim

esapi_startup_getrandom_mssim: esapi_startup_getrandom_mssim.c
    cl -I "D:\git\tpm2-tss\include" esapi_startup_getrandom_mssim.c /link /LIBPATH:"D:\usr\local\lib" tss2-esys.lib tss2-tctildr.lib tss2-tcti-mssim.lib
