all: esapi_getrandom

esapi_getrandom: esapi_getrandom.c
   cl /Fo".\target\esapi_getrandom" /Fe".\target\esapi_getrandom.exe" -I "D:\git\tpm2-tss\include" esapi_getrandom.c /link /LIBPATH:"D:\usr\local\lib" tss2-esys.lib tss2-tctildr.lib 

